### ISSUE TITLE
Insert font properties

### ISSUE THREAD

**Issue by ai** [dan-gamble/postcss-font-awesome#1]
Maybe this plugin should also insert a `font-family` and orther properties?

**Comment by dan-gamble** [comment]
:+1: Already writing for v `0.2.0` :D

I've never created a npm package before so i wanted to start with a base so i can learn the release process as well :)

**Comment by ai** [comment]
https://github.com/FortAwesome/Font-Awesome/blob/master/scss/_core.scss#L5-L10

**Comment by ai** [comment]
Yeap, Getting Real is always good way. Start with prototype and then add more features in next releases.

**Comment by dan-gamble** [comment]
Thanks! I think i'll insert everything except the `font-size` so i can leave that up to the user :)

**Comment by dan-gamble** [comment]
Added in 0.2.0 https://github.com/dan-gamble/postcss-font-awesome/releases/tag/0.2.0 :)
